# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foodfinder/supplier/supplier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foodfinder/supplier/supplier.proto',
  package='foodfinder.supplier',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"foodfinder/supplier/supplier.proto\x12\x13\x66oodfinder.supplier\"*\n\x14SearchVendorsRequest\x12\x12\n\ningredient\x18\x01 \x01(\t\"*\n\x15SearchVendorsResponse\x12\x11\n\tvendorIds\x18\x01 \x03(\x03\x32t\n\x08Supplier\x12h\n\rsearchVendors\x12).foodfinder.supplier.SearchVendorsRequest\x1a*.foodfinder.supplier.SearchVendorsResponse\"\x00\x62\x06proto3'
)




_SEARCHVENDORSREQUEST = _descriptor.Descriptor(
  name='SearchVendorsRequest',
  full_name='foodfinder.supplier.SearchVendorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredient', full_name='foodfinder.supplier.SearchVendorsRequest.ingredient', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=101,
)


_SEARCHVENDORSRESPONSE = _descriptor.Descriptor(
  name='SearchVendorsResponse',
  full_name='foodfinder.supplier.SearchVendorsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendorIds', full_name='foodfinder.supplier.SearchVendorsResponse.vendorIds', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['SearchVendorsRequest'] = _SEARCHVENDORSREQUEST
DESCRIPTOR.message_types_by_name['SearchVendorsResponse'] = _SEARCHVENDORSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchVendorsRequest = _reflection.GeneratedProtocolMessageType('SearchVendorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHVENDORSREQUEST,
  '__module__' : 'foodfinder.supplier.supplier_pb2'
  # @@protoc_insertion_point(class_scope:foodfinder.supplier.SearchVendorsRequest)
  })
_sym_db.RegisterMessage(SearchVendorsRequest)

SearchVendorsResponse = _reflection.GeneratedProtocolMessageType('SearchVendorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHVENDORSRESPONSE,
  '__module__' : 'foodfinder.supplier.supplier_pb2'
  # @@protoc_insertion_point(class_scope:foodfinder.supplier.SearchVendorsResponse)
  })
_sym_db.RegisterMessage(SearchVendorsResponse)



_SUPPLIER = _descriptor.ServiceDescriptor(
  name='Supplier',
  full_name='foodfinder.supplier.Supplier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=263,
  methods=[
  _descriptor.MethodDescriptor(
    name='searchVendors',
    full_name='foodfinder.supplier.Supplier.searchVendors',
    index=0,
    containing_service=None,
    input_type=_SEARCHVENDORSREQUEST,
    output_type=_SEARCHVENDORSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPPLIER)

DESCRIPTOR.services_by_name['Supplier'] = _SUPPLIER

# @@protoc_insertion_point(module_scope)
