# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from foodfinder.finder import finder_pb2 as foodfinder_dot_finder_dot_finder__pb2


class FinderStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.findIngredient = channel.unary_unary(
                '/foodfinder.finder.Finder/findIngredient',
                request_serializer=foodfinder_dot_finder_dot_finder__pb2.FindIngredientRequest.SerializeToString,
                response_deserializer=foodfinder_dot_finder_dot_finder__pb2.FindIngredientResponse.FromString,
                )


class FinderServicer(object):
    """Missing associated documentation comment in .proto file"""

    def findIngredient(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'findIngredient': grpc.unary_unary_rpc_method_handler(
                    servicer.findIngredient,
                    request_deserializer=foodfinder_dot_finder_dot_finder__pb2.FindIngredientRequest.FromString,
                    response_serializer=foodfinder_dot_finder_dot_finder__pb2.FindIngredientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foodfinder.finder.Finder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Finder(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def findIngredient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/foodfinder.finder.Finder/findIngredient',
            foodfinder_dot_finder_dot_finder__pb2.FindIngredientRequest.SerializeToString,
            foodfinder_dot_finder_dot_finder__pb2.FindIngredientResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
